name: Documentation checks

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: '**/*.md'
      - name: Check links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress README.md CONTRIBUTING.md CODE_OF_CONDUCT.md SECURITY.md
          fail: true
